# Generated by Django 5.2.6 on 2025-09-07 16:11

import acervo.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EixoOrganizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eixo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('local', models.CharField(max_length=255)),
                ('orgazador', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LocalInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('fones', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('naturalidade', models.CharField(blank=True, max_length=40, null=True)),
                ('nacionalidade', models.CharField(blank=True, max_length=20, null=True)),
                ('nascimento', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=acervo.models.hoje)])),
                ('biografia', models.TextField(null=True)),
                ('pessoa_fisica', models.BooleanField(default=True)),
                ('autor_de_obra', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PecasAcervo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacao', models.CharField(max_length=100)),
                ('titulo_dado_pelo_autor', models.CharField(max_length=100)),
                ('nr_registro', models.CharField(blank=True, max_length=10, null=True)),
                ('numero_ordem', models.CharField(blank=True, max_length=3, null=True)),
                ('situacao', models.CharField(choices=[('LC', 'Localizado'), ('NL', 'Não localizado'), ('EX', 'Excluído')], default='LC', max_length=2)),
                ('thesaurus', models.CharField(blank=True, max_length=100, null=True)),
                ('resumo_descritivo', models.TextField()),
                ('dimensoes', models.CharField(blank=True, max_length=30, null=True)),
                ('material_tecnica', models.TextField()),
                ('estado_conservacao', models.CharField(choices=[('BOM', 'Bom'), ('RAZ', 'Razoável'), ('RUI', 'Ruim'), ('INT', 'Inutilizada')], max_length=3)),
                ('local_producao', models.CharField(max_length=200)),
                ('data_inicial_producao', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=acervo.models.hoje)])),
                ('data_final_producao', models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=acervo.models.hoje)])),
                ('pode_reproduzir', models.BooleanField(default=False)),
                ('condicoes_reproducao', models.TextField(blank=True, null=True)),
                ('tipologia', models.CharField(choices=[('MUS', 'Museológico'), ('BIB', 'Bibliográfico'), ('ARQ', 'Arquivístico')], default='MUS', max_length=3)),
                ('forma_aquisicao', models.CharField(choices=[('DOA', 'Doação'), ('CMP', 'Compra'), ('EMP', 'Empréstimo/Depósito'), ('LEG', 'Legado'), ('PMT', 'Permuta'), ('PRE', 'Premiação'), ('TRF', 'Transferência')], max_length=3)),
                ('publicada', models.BooleanField(default=False)),
                ('eixo_organizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acervo.eixoorganizador')),
                ('exposicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acervo.exposicao')),
                ('localizacao_interna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acervo.localinterno')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acervo.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('F', 'Foto/Digitalização'), ('V', 'Vídeo'), ('A', 'Áudio')], default='F', max_length=1)),
                ('peca_acervo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervo.pecasacervo')),
            ],
        ),
    ]
