# Generated by Django 5.2.6 on 2025-09-07 21:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEventoPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_evento', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='HistoricoPecas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField(default=datetime.date.today)),
                ('data_final', models.DateField(default=datetime.date.today)),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervo.pecasacervo')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='acervo.pessoa')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acervo.tipoeventopeca')),
            ],
        ),
    ]
