# Generated by Django 5.2.6 on 2025-09-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0002_tipoeventopeca_alter_pessoa_email_historicopecas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eixoorganizador',
            options={'verbose_name': 'Eixo Organizador', 'verbose_name_plural': 'Eixos Organizadores'},
        ),
        migrations.AlterModelOptions(
            name='exposicao',
            options={'verbose_name': 'Exposição', 'verbose_name_plural': 'Exposições'},
        ),
        migrations.AlterModelOptions(
            name='historicopecas',
            options={'verbose_name': 'Histórico da Peça', 'verbose_name_plural': 'Históricos da Peça'},
        ),
        migrations.AlterModelOptions(
            name='localinterno',
            options={'verbose_name': 'Local Interno', 'verbose_name_plural': 'Locais Internos'},
        ),
        migrations.AlterModelOptions(
            name='midia',
            options={'verbose_name': 'Mídia', 'verbose_name_plural': 'Mídias'},
        ),
        migrations.AlterModelOptions(
            name='pecasacervo',
            options={'verbose_name': 'Peça', 'verbose_name_plural': 'Peças'},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AlterModelOptions(
            name='tipoeventopeca',
            options={'verbose_name': 'Tipo do Evento da Peça', 'verbose_name_plural': 'Tipos dos Eventos da Peça'},
        ),
        migrations.AddField(
            model_name='midia',
            name='legenda',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='midia',
            name='url_midia',
            field=models.FileField(null=True, upload_to='acervo/'),
        ),
    ]
