# Generated by Django 5.2.6 on 2025-09-07 23:56

import acervo.models
import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0003_alter_eixoorganizador_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eixoorganizador',
            name='eixo',
            field=models.CharField(max_length=100, verbose_name='Eixo'),
        ),
        migrations.AlterField(
            model_name='exposicao',
            name='data_final',
            field=models.DateField(verbose_name='Data de encerramento'),
        ),
        migrations.AlterField(
            model_name='exposicao',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='exposicao',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='exposicao',
            name='local',
            field=models.CharField(max_length=255, verbose_name='Local(ais)'),
        ),
        migrations.AlterField(
            model_name='exposicao',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Exposição'),
        ),
        migrations.AlterField(
            model_name='exposicao',
            name='orgazador',
            field=models.CharField(max_length=200, verbose_name='Organizador(es)'),
        ),
        migrations.AlterField(
            model_name='historicopecas',
            name='data_final',
            field=models.DateField(default=datetime.date.today, verbose_name='Data final'),
        ),
        migrations.AlterField(
            model_name='historicopecas',
            name='data_inicio',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='historicopecas',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhamento do evento'),
        ),
        migrations.AlterField(
            model_name='localinterno',
            name='local',
            field=models.CharField(max_length=100, verbose_name='Local na ACORDE'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='tipo',
            field=models.CharField(choices=[('F', 'Foto/Digitalização'), ('V', 'Vídeo'), ('A', 'Áudio')], default='F', max_length=1, verbose_name='Tipo da mídia'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='url_midia',
            field=models.FileField(null=True, upload_to='acervo/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='pecasacervo',
            name='condicoes_reproducao',
            field=models.TextField(blank=True, null=True, verbose_name='Condições da reprodução'),
        ),
        migrations.AlterField(
            model_name='pecasacervo',
            name='data_final_producao',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=acervo.models.hoje)], verbose_name='Data final produção'),
        ),
        migrations.AlterField(
            model_name='pecasacervo',
            name='data_inicial_producao',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=acervo.models.hoje)], verbose_name='Data inicial produção'),
        ),
        migrations.AlterField(
            model_name='pecasacervo',
            name='denominacao',
            field=models.CharField(max_length=100, verbose_name='Nome da peça'),
        ),
        migrations.AlterField(
            model_name='pecasacervo',
            name='dimensoes',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Dimensões'),
        ),
        migrations.AlterField(
            model_name='pecasacervo',
            name='estado_conservacao',
            field=models.CharField(choices=[('BOM', 'Bom'), ('RAZ', 'Razoável'), ('RUI', 'Ruim'), ('INT', 'Inutilizada')], max_length=3, verbose_name='Estado de conservação'),
        ),
        migrations.AlterField(
            model_name='pecasacervo',
            name='forma_aquisicao',
            field=models.CharField(choices=[('DOA', 'Doação'), ('CMP', 'Compra'), ('EMP', 'Empréstimo/Depósito'), ('LEG', 'Legado'), ('PMT', 'Permuta'), ('PRE', 'Premiação'), ('TRF', 'Transferência')], max_length=3, verbose_name='Forma de aquisição'),
        ),
        migrations.AlterField(
            model_name='pecasacervo',
            name='local_producao',
            field=models.CharField(max_length=200, verbose_name='Local onde foi produzida'),
        ),
        migrations.AlterField(
            model_name='pecasacervo',
            name='material_tecnica',
            field=models.TextField(verbose_name='Tipo de material e técnica'),
        ),
        migrations.AlterField(
            model_name='pecasacervo',
            name='nr_registro',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Nº registro'),
        ),
        migrations.AlterField(
            model_name='pecasacervo',
            name='numero_ordem',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Nº de ordem'),
        ),
        migrations.AlterField(
            model_name='pecasacervo',
            name='pode_reproduzir',
            field=models.BooleanField(default=False, verbose_name='Pode reproduzir?'),
        ),
        migrations.AlterField(
            model_name='pecasacervo',
            name='publicada',
            field=models.BooleanField(default=False, verbose_name='Publicar no site'),
        ),
        migrations.AlterField(
            model_name='pecasacervo',
            name='resumo_descritivo',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='pecasacervo',
            name='situacao',
            field=models.CharField(choices=[('LC', 'Localizado'), ('NL', 'Não localizado'), ('EX', 'Excluído')], default='LC', max_length=2, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='pecasacervo',
            name='thesaurus',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Thesaurus'),
        ),
        migrations.AlterField(
            model_name='pecasacervo',
            name='tipologia',
            field=models.CharField(choices=[('MUS', 'Museológico'), ('BIB', 'Bibliográfico'), ('ARQ', 'Arquivístico')], default='MUS', max_length=3, verbose_name='Tipologia'),
        ),
        migrations.AlterField(
            model_name='pecasacervo',
            name='titulo_dado_pelo_autor',
            field=models.CharField(max_length=100, verbose_name='Título dado pelo autor'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='autor_de_obra',
            field=models.BooleanField(default=True, verbose_name='Autor de obra?'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='biografia',
            field=models.TextField(null=True, verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email(s)'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='fones',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Fone(s)'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nacionalidade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nascimento',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=acervo.models.hoje)], verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='naturalidade',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Natural'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pessoa_fisica',
            field=models.BooleanField(default=True, verbose_name='Pessoa física?'),
        ),
        migrations.AlterField(
            model_name='tipoeventopeca',
            name='desc_evento',
            field=models.CharField(max_length=100, verbose_name='Tipo do evento'),
        ),
    ]
