# Generated by Django 5.2.6 on 2025-09-08 00:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0004_alter_eixoorganizador_eixo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midia',
            name='url_midia',
            field=models.FileField(null=True, upload_to='acervo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi', 'mkv', 'mp3', 'wav', 'ogg'])], verbose_name='Arquivo'),
        ),
    ]
