# Generated by Django 5.2.6 on 2025-09-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0005_alter_midia_url_midia'),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='data_upload',
            field=models.DateField(auto_now_add=True, default="2025-07-09", verbose_name='Data upload'),
            preserve_default=False,
        ),
    ]
