# Generated by Django 5.2.6 on 2025-10-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0006_midia_data_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pecasacervo',
            name='autor',
        ),
        migrations.AddField(
            model_name='pecasacervo',
            name='autor',
            field=models.ManyToManyField(blank=True, null=True, to='acervo.pessoa', verbose_name='Autores(as)'),
        ),
    ]
