# Generated by Django 5.2.6 on 2025-11-01 22:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0007_remove_pecasacervo_autor_pecasacervo_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposicao',
            name='exposicao_fisica',
            field=models.BooleanField(default=True, verbose_name='Exposicação física'),
        ),
        migrations.AlterField(
            model_name='historicopecas',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acervo.pessoa'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='peca_acervo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='acervo.pecasacervo'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='url_midia',
            field=models.FileField(null=True, upload_to='acervo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'avi', 'mkv', 'mp3', 'wav', 'ogg', 'pdf', 'pdf'])], verbose_name='Arquivo'),
        ),
    ]
