# Generated by Django 5.2.6 on 2025-11-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0008_exposicao_exposicao_fisica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pecasacervo',
            name='autor',
            field=models.ManyToManyField(blank=True, to='acervo.pessoa', verbose_name='Autores(as)'),
        ),
    ]
