# Generated by Django 5.2.6 on 2025-11-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0009_alter_pecasacervo_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_ia_key', models.TextField(blank=True, null=True, verbose_name='Chave da OpenAI')),
            ],
            options={
                'verbose_name': 'Configuracao do sistema',
                'verbose_name_plural': 'Configuracoes do sistema',
            },
        ),
    ]
