# Generated by Django 5.2.6 on 2025-11-04 01:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0011_alter_configs_open_ia_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='audio_descricao',
            field=models.FileField(blank=True, null=True, upload_to='acervo/audiodescricoes', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'ogg'])], verbose_name='Áudiodescrição'),
        ),
        migrations.AddField(
            model_name='midia',
            name='texto_descricao',
            field=models.TextField(blank=True, verbose_name='Texto de descrição'),
        ),
    ]
