# Generated by Django 5.2.6 on 2025-11-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0012_midia_audio_descricao_midia_texto_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='qrcode_midia',
            field=models.ImageField(blank=True, null=True, upload_to='acervo/qrcodes', verbose_name='QRCode da mídia'),
        ),
    ]
